Repository AY2021S2-CS2103T-W15-2/tp, pull requests merged in 2021-04, with the labels that each got.

#74 Add Meeting
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/meet-add.png
  docs/images/meet-clash.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/MeetCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/attribute/Attribute.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/person/MeetingContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedMeeting.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MeetCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MeetCommandParserTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#104 Remove clear command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UndoRedoState5.puml
  docs/images/UndoRedoState5.png
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task

#101 Batch command + documentation + testing
  docs/UserGuide.md
  docs/diagrams/LogicClassDiagram.puml
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/BatchCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/BatchCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/BatchCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/BatchCommandParserTest.java
Labels: type.Feature

#108 Fix compilation error where shortcut library was not included
  src/main/java/seedu/address/logic/commands/AddShortcutCommand.java
  src/main/java/seedu/address/logic/commands/BatchCommand.java
  src/main/java/seedu/address/logic/parser/AddShortcutCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteShortcutCommandParser.java
  src/main/java/seedu/address/logic/parser/EditShortcutCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/AddShortcutCommandTest.java
  src/test/java/seedu/address/logic/commands/BatchCommandTest.java
Labels: type.Bug

#99 Change edit to be able to modify/insert/remove instead of only replace
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/attribute/Attribute.java
  src/test/data/LockTest/keystore
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Enhancement

#105 Change ug
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/alexYeohChangePhone.png
  docs/images/cleanUi.png
  docs/images/newContactJames.png
  docs/images/typeCommandHere.png
  docs/img.png
  docs/index.md
Labels: type.Documentation

#111 Update UG and DG links and Codecov badge in index.md
  docs/index.md
Labels: type.Documentation

#114 Change version number in MainApp
  src/main/java/seedu/address/MainApp.java
Labels: type.Documentation

#117 Change person to client in messages
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.Bug

#118 Update DG for new edit command
  docs/DeveloperGuide.md
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/EditSequenceDiagram.png
Labels: type.Documentation

#180 Change PoliciesWindow title to a general title
  src/main/java/seedu/address/ui/PoliciesWindow.java
  src/test/data/LockTest/keystore
Labels: type.Bug

#182 Update image to fit new policy window UI
  docs/images/with-policy-URL-annotate.png
Labels: type.Documentation

#186 Add PPP (wongkokian.md)
  docs/team/wongkokian.md
Labels: type.Documentation

#179 Fix bug that allowed adding duplicate policies
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug

#170 Update landing page with introduction
  README.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
Labels: type.Documentation

#187 Edit UML diagram to show PoliciesWindow class + Update to show correct error messages for invalid indices
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/parser/PolicyCommandParser.java
  src/test/java/seedu/address/logic/commands/PolicyCommandTest.java
  src/test/java/seedu/address/logic/parser/PolicyCommandParserTest.java
Labels: type.Bug

#185 Update DG to include shortcut feature
  docs/DeveloperGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ShortcutSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ShortcutSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Documentation

#190 Fix minor bugs/typos in DG
  docs/DeveloperGuide.md
  docs/images/UndoRedoState5.png
Labels: type.Bug

#168 Add basic URL parsing for policies
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/insurancepolicy/InsurancePolicy.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/insurancepolicy/InsurancePolicyTest.java
Labels: type.Bug

#192 Update DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#196 Bug fixes
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/commands/BatchCommand.java
  src/main/java/seedu/address/logic/parser/BatchCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PolicyCommandParser.java
  src/main/java/seedu/address/model/insurancepolicy/InsurancePolicy.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/parser/BatchCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/insurancepolicy/InsurancePolicyTest.java
Labels: type.Bug

#197 Fix documentation bugs and shortcut feature error messages
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/images/Ui-annotate.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/addshortcut.png
  docs/images/listshortcut.png
  docs/images/shortcut-example.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddShortcutCommand.java
  src/main/java/seedu/address/logic/commands/EditShortcutCommand.java
  src/main/java/seedu/address/model/shortcut/Shortcut.java
  src/test/data/LockTest/keystore
Labels: type.Bug

#194 Update DG logic diagram + formatting issues
  docs/DeveloperGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/ParserClassDiagram.png
Labels: type.Documentation

#202 Fix shortcut bug + enable duplicate names
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListShortcutCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/shortcut/Shortcut.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Bug

#204 Fix compilation error in master
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/data/LockTest/keystore
Labels: type.Bug

#215 Fix UG Logo
  docs/Gemfile
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/images/logo.png
Labels: type.Bug

#216 Fix error messages
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/BatchCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/BatchCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/data/LockTest/keystore
  src/test/java/seedu/address/logic/parser/BatchCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Bug

#227 Update PPP and add portfolio link to Github Pages
  docs/AboutUs.md
  docs/team/wongkokian.md
  src/test/data/LockTest/keystore
Labels: type.Documentation
