Repository AY2021S2-CS2103T-W15-2/tp, pull requests merged in 2021-03, with the labels that each got.

#26 Update links to UG and DG
  README.md
  docs/index.md
Labels: type.documentation

#28 Update user guide for ClientBook
  docs/UserGuide.md
Labels: type.documentation

#41 Sorting clients by name
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ModifiableAddressBook.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Story

#43 Add display policy url
  docs/UserGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  docs/images/with_policy_URL.png
  docs/images/without_policy_url.png
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/PolicyCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PolicyCommandParser.java
  src/main/java/seedu/address/model/insurancepolicy/InsurancePolicy.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedInsurancePolicy.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PoliciesWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PoliciesWindow.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Feature

#40 Add lock, unlock functionality
  .github/check-eof-newline.sh
  README.md
  build.gradle
  config/travis/check-eof-newline.sh
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/LockCommand.java
  src/main/java/seedu/address/logic/commands/UnlockCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/LockCommandParser.java
  src/main/java/seedu/address/logic/parser/UnlockCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/Authentication.java
  src/test/data/LockTest/keystore
  src/test/data/keystore
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/LockCommandTest.java
  src/test/java/seedu/address/logic/commands/UnlockCommandTest.java
Labels: type.Story

#44 Modify find command for multiple queries and search by field
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/find_alex_&_david.png
  docs/images/find_alex_david.png
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/InsurancePolicyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/InsurancePolicyContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
Labels: type.Feature

#46 Add Sorting for Policy
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Feature

#51 Tests for policy command
  src/main/java/seedu/address/logic/commands/PolicyCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedInsurancePolicy.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PoliciesWindow.java
  src/test/java/seedu/address/logic/commands/PolicyCommandTest.java
  src/test/java/seedu/address/logic/parser/PolicyCommandParserTest.java
Labels: type.Test

#53 Add tests for UnlockCommand, LockCommand, Authentication, InsurancePolicy
  src/main/java/seedu/address/logic/commands/UnlockCommand.java
  src/main/java/seedu/address/storage/Authentication.java
  src/test/data/LockTest/addressbook.json
  src/test/data/LockTest/keystore
  src/test/java/seedu/address/logic/commands/LockCommandTest.java
  src/test/java/seedu/address/logic/commands/UnlockCommandTest.java
  src/test/java/seedu/address/model/insurancepolicy/InsurancePolicyTest.java
  src/test/java/seedu/address/storage/AuthenticationTest.java
Labels: type.Test

#56 Add author tags
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/InsurancePolicyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/InsurancePolicyContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
Labels: type.Bug

#55 Filter find by attributes and allow filter with multiple attributes
  docs/UserGuide.md
  docs/images/find_alex_&_david.png
  docs/images/find_alex_&_david_with_filter.png
  docs/images/find_alex_david.png
  docs/images/list_with_filter.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: type.Enhancement

#72 Enable assertions in Gradle run task
  build.gradle
Labels: type.Task

#82 Update DG with PolicyCommand Implementation
  docs/DeveloperGuide.md
  docs/diagrams/PolicyCommandDiagram.puml
  docs/diagrams/style.puml
  docs/images/PolicyCommandDiagram.png
Labels: type.Documentation

#90 Add annotations to UG screenshots
  docs/UserGuide.md
  docs/images/delete-2.png
  docs/images/edit-1.png
  docs/images/edit-annotate.png
  docs/images/find-alex-&-david-with-filter-annotate.png
  docs/images/find-alex-&-david-with-filter.png
  docs/images/find-alex-&-david.png
  docs/images/find_alex_david-annotate.png
  docs/images/find_alex_david.png
  docs/images/list-phone-policy-annotate.png
  docs/images/list-phone-policy.png
  docs/images/sort-des-annotate.png
  docs/images/sort-des.png
  docs/images/with-policy-URL-annotate.png
  docs/images/with_policy_URL.png
Labels: type.Documentation

#91 Update UG
  docs/UserGuide.md
  docs/images/delete-2.png
  docs/images/delete-charlotte.png
  docs/images/lock-new-pw.png
  docs/images/lock-update-pw.png
  docs/images/unlock-correct-pw.png
  docs/images/unlock-wrong-pw.png
Labels: type.Documentation

#58 Add keyboard shortcuts
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Story
